# Generated by Django 4.2.2 on 2023-06-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('handle', models.CharField(max_length=100)),
                ('friends', models.ManyToManyField(to='chat.profile')),
            ],
        ),
    ]
