# Generated by Django 4.2.2 on 2023-06-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile_user_alter_profile_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='handle',
            new_name='name',
        ),
    ]
