# Generated by Django 4.2.2 on 2023-06-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.profile')),
            ],
        ),
    ]
