# Generated by Django 4.2.2 on 2023-06-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.profile'),
        ),
    ]
