# Generated by Django 4.2.2 on 2023-06-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rename_image_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(null=True, upload_to='db_files/pfps'),
        ),
    ]
