# Generated by Django 4.2.2 on 2023-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_profile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(null=True, upload_to='pfps/'),
        ),
    ]
